### ISSUE TITLE
Attack / Slash Guard needs to be updated

### ISSUE THREAD

**Issue by Shamanon** [5p0ng3b0b/bitburner-scripts#1]
On line 120: change "slash" to "attack"
On line 134: change "ATTACKING!" to "Preparing?"

Thanks for this script, it's awesome!

**Comment by 5p0ng3b0b** [comment]
have not played for about a year. had a god mode script that basically levelled up after about 10 clicks lol

**Comment by Shamanon** [comment]
Ok... thanks for your hard work... the autoinfiletrate script has been a huge help!

**Comment by 5p0ng3b0b** [comment]
I got around to changing it. Thanks
